# Makefile configuration
# This is included from every makefile, for common options that you might
# want to set. There should be no targets in here.

ifndef MAKEFILE_CONFIG_
MAKEFILE_CONFIG_:=1

BUILD_VERBOSE := 0

ifeq ($(BUILD_VERBOSE), 1)
	Q :=
	echo := @true
else
	Q := @
	echo := @echo
endif

echo_recurse := $(echo) " >>> "
echo_leave   := $(echo) " <<< "
MKOPTS := --no-print-directory

CC=mingw32-gcc
CXX=mingw32-g++
CFLAGS=-O2 -Wall
CXXFLAGS=-O2 -Wall -g

rm=rm -f

export Q
export echo
export echo_recurse
export echo_leave
export MKOPTS

endif
